/**
 * Ballot API — wraps the compiled contract for use in the frontend.
 *
 * Currently runs in SIMULATOR MODE (no proof server needed).
 * Circuit calls execute locally and state is kept in memory.
 * Swap in on-chain calls here once the Preprod deployment is live.
 */

import * as runtime from '@midnight-ntwrk/compact-runtime';

// Generated by `npm run compact` in the repo root
import {
  Contract,
  ledger,
  type Ledger,
} from '../../../src/managed/ballot/contract/index.js';

export type { Ledger };

export type BallotState = {
  isOpen: boolean;
  proposal: string | null;
  yesVotes: bigint;
  noVotes: bigint;
  organizer: Uint8Array;
};

export type OrganizerKey = Uint8Array;

const DUMMY_KEY: runtime.EncodedCoinPublicKey = { bytes: new Uint8Array(32) };

export class BallotAPI {
  private contract: Contract<null>;
  private contractState: runtime.ContractState;
  private privateState: null = null;
  private zswapState: runtime.EncodedZswapLocalState;

  constructor(organizerKey: OrganizerKey) {
    this.contract = new Contract({
      organizerKey: (_ctx) => [null, organizerKey],
    });

    const init = this.contract.initialState(
      runtime.createConstructorContext(null, DUMMY_KEY),
    );
    this.contractState = init.currentContractState;
    this.privateState = init.currentPrivateState;
    this.zswapState = init.currentZswapLocalState;
  }

  getState(): BallotState {
    const l = ledger(this.contractState.data);
    return {
      isOpen: l.isOpen === 1n,
      proposal: l.proposal.is_some ? l.proposal.value : null,
      yesVotes: l.yesVotes,
      noVotes: l.noVotes,
      organizer: l.organizer,
    };
  }

  private ctx(): runtime.CircuitContext<null> {
    return runtime.createCircuitContext(
      runtime.dummyContractAddress(),
      this.zswapState.coinPublicKey,
      this.contractState.data,
      this.privateState,
    );
  }

  private sync(result: runtime.CircuitResults<null, unknown>): void {
    this.contractState.data = new runtime.ChargedState(
      result.context.currentQueryContext.state.state,
    );
    this.privateState = result.context.currentPrivateState;
    this.zswapState = result.context.currentZswapLocalState;
  }

  async openBallot(proposal: string): Promise<void> {
    this.sync(this.contract.circuits.openBallot(this.ctx(), proposal));
  }

  async castVote(vote: 'yes' | 'no'): Promise<void> {
    if (vote === 'yes') {
      this.sync(this.contract.circuits.castYes(this.ctx()));
    } else {
      this.sync(this.contract.circuits.castNo(this.ctx()));
    }
  }

  async closeBallot(): Promise<void> {
    this.sync(this.contract.circuits.closeBallot(this.ctx()));
  }
}
