/**
 * Night Ballot — deployment script for Midnight Preprod / Preview
 *
 * Prerequisites:
 *   1. Toolchain installed (compact, Node 22, Docker)
 *   2. Contract compiled: npm run compact
 *   3. Proof server running: docker run -p 6300:6300 midnightntwrk/proof-server:latest
 *   4. .env file populated (copy .env.example and fill in values)
 *      - ORGANIZER_KEY: 64-char hex (32 bytes) organizer secret key
 *      - WALLET_SEED: BIP-39 mnemonic for the deployer wallet
 *      - NETWORK: preprod | preview  (default: preprod)
 *      - PROOF_SERVER_URL: proof server URL (default: http://localhost:6300)
 *
 * Usage:
 *   npm run deploy
 *
 * The script will:
 *   - Connect to the Preprod indexer and proof server
 *   - Deploy the ballot contract using deployContract() from midnight-js-contracts
 *   - Print the contract address (copy this to your .env as CONTRACT_ADDRESS)
 */

import 'dotenv/config';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import type { MidnightProviders, PrivateStateId } from '@midnight-ntwrk/midnight-js-types';
import { createWitnesses } from './witnesses.js';

// Generated by `npm run compact` — run that command first
import { Contract, ledger } from './managed/ballot/contract/index.js';

// ---------------------------------------------------------------------------
// Network configuration
// ---------------------------------------------------------------------------

const NETWORK = (process.env['NETWORK'] ?? 'preprod') as 'preprod' | 'preview';

const INDEXER_URLS: Record<string, { query: string; ws: string }> = {
  preprod: {
    query: 'https://indexer.testnet-02.midnight.network/api/v1/graphql',
    ws: 'wss://indexer.testnet-02.midnight.network/api/v1/graphql/ws',
  },
  preview: {
    query: 'https://indexer.testnet.midnight.network/api/v1/graphql',
    ws: 'wss://indexer.testnet.midnight.network/api/v1/graphql/ws',
  },
};

const PROOF_SERVER_URL = process.env['PROOF_SERVER_URL'] ?? 'http://localhost:6300';
const __dirname = dirname(fileURLToPath(import.meta.url));
// NodeZkConfigProvider expects a directory that contains <circuitId>.prover,
// <circuitId>.verifier, and <circuitId>.bzkir files
const MANAGED_DIR = join(__dirname, 'managed', 'ballot', 'keys');

// ---------------------------------------------------------------------------
// In-memory private state provider  (ballot contract has null private state)
// ---------------------------------------------------------------------------

function inMemoryPrivateStateProvider() {
  const store = new Map<string, null>();
  return {
    get: async (id: string): Promise<null> => store.get(id) ?? null,
    set: async (id: string, state: null): Promise<void> => { store.set(id, state); },
    remove: async (id: string): Promise<void> => { store.delete(id); },
  };
}

// ---------------------------------------------------------------------------
// Deploy
// ---------------------------------------------------------------------------

async function deploy(): Promise<void> {
  console.log(`\nNight Ballot — deploying to ${NETWORK}`);
  console.log('─'.repeat(50));

  const networkUrls = INDEXER_URLS[NETWORK];
  if (!networkUrls) throw new Error(`Unknown network: ${NETWORK}`);

  console.log(`Indexer  : ${networkUrls.query}`);
  console.log(`Proof srv: ${PROOF_SERVER_URL}`);

  const witnesses = createWitnesses();

  // Build the Contract instance with the organizer key witness
  const contract = new Contract({
    organizerKey: (_ctx: unknown) => [null, witnesses.organizerKey()] as [null, Uint8Array],
  });

  // ZK config provider reads proving/verifying keys + ZKIR from managed/ballot/keys/
  const zkConfigProvider = new NodeZkConfigProvider<string>(MANAGED_DIR);

  // Indexer public data provider — subscribes to blockchain state via GraphQL
  const publicDataProvider = indexerPublicDataProvider(
    networkUrls.query,
    networkUrls.ws,
  );

  // HTTP proof provider — delegates ZK proof generation to the local proof server
  const proofProvider = httpClientProofProvider(PROOF_SERVER_URL, zkConfigProvider);

  // Wallet provider — the deployer wallet that pays fees and balances transactions.
  // Midnight's wallet-sdk provides a full HD wallet from a BIP-39 seed phrase.
  // See @midnight-ntwrk/wallet-sdk and testkit-js for wallet initialization helpers.
  const mnemonic = process.env['WALLET_SEED'];
  if (!mnemonic) throw new Error('WALLET_SEED is required in .env for deployment');

  // Dynamic import so type errors in the wallet-sdk don't block compilation
  // when wallet-sdk types are still evolving.
  const { WalletBuilder } = await import('@midnight-ntwrk/wallet-sdk' as any);
  const wallet = await WalletBuilder.buildFromMnemonic(mnemonic, {
    indexerUri: networkUrls.query,
    indexerWsUri: networkUrls.ws,
    proofServerUri: PROOF_SERVER_URL,
  });
  await wallet.sync();

  const walletProvider = {
    balanceTx: (tx: any, ttl?: Date) => wallet.balanceTx(tx, ttl),
    getCoinPublicKey: () => wallet.getCoinPublicKey(),
    getEncryptionPublicKey: () => wallet.getEncryptionPublicKey(),
  };

  const { IndexerClient } = await import('@midnight-ntwrk/wallet-sdk' as any);
  const indexerClient = IndexerClient.create(networkUrls.query);
  const midnightProvider = {
    submitTx: (tx: any) => indexerClient.submitTransaction(tx),
  };

  // Assemble all providers required by midnight-js-contracts
  const providers: MidnightProviders<string, PrivateStateId, null> = {
    privateStateProvider: inMemoryPrivateStateProvider() as any,
    publicDataProvider,
    zkConfigProvider,
    proofProvider,
    walletProvider: walletProvider as any,
    midnightProvider: midnightProvider as any,
  };

  console.log('\nDeploying ballot contract via deployContract()…');

  // deployContract() builds the initial contract state, generates ZK proofs,
  // balances the transaction with the wallet, and submits it to the network.
  const deployed = await deployContract(providers as any, {
    compiledContract: contract as any,
    privateStateId: 'ballot',
    initialPrivateState: null,
  } as any);

  const contractAddress = (deployed as any).deployTxData?.public?.contractAddress
    ?? (deployed as any).contractAddress;

  console.log('\n✓ Contract deployed!');
  console.log(`  Address : ${contractAddress}`);
  console.log(`  Network : Midnight ${NETWORK}`);

  const state = ledger((deployed as any).deployTxData?.public?.initialContractState?.data);
  console.log(`  Is open : ${state.isOpen === 1n}`);

  console.log('\nAdd to .env:');
  console.log(`  CONTRACT_ADDRESS=${contractAddress}`);
  console.log('\nUpdate README.md table row:');
  console.log(`  | **Contract Address** | \`${contractAddress}\` (Midnight ${NETWORK}) |`);
}

deploy().catch((err) => {
  console.error('Deployment failed:', err);
  process.exit(1);
});
