/**
 * Night Ballot — deployment script for Midnight Preprod
 *
 * Prerequisites (all must be ready before running):
 *   1. Contract compiled:  npm run compact
 *   2. Docker running the proof server:
 *        docker run -p 6300:6300 midnightntwrk/proof-server:latest midnight-proof-server -v
 *   3. .env populated (copy .env.example):
 *        ORGANIZER_KEY=<64-hex-char secret>
 *        WALLET_SEED=<BIP-39 mnemonic from your Lace Midnight wallet>
 *        NETWORK=preprod
 *        PROOF_SERVER_URL=http://localhost:6300
 *   4. Wallet funded with tMIDN from https://midnight.network/test-faucet
 *
 * Usage:
 *   npm run deploy
 *
 * On success the script prints CONTRACT_ADDRESS=<hex>.
 * Copy that into .env and update the README.md table.
 */

import 'dotenv/config';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import {
  PreprodTestEnvironment,
  PreviewTestEnvironment,
  MidnightWalletProvider,
  initializeMidnightProviders,
  inMemoryPrivateStateProvider,
  createDefaultTestLogger,
} from '@midnight-ntwrk/testkit-js';

import { createWitnesses } from './witnesses.js';
// Generated by `npm run compact` — run that command first
import { Contract, ledger } from './managed/ballot/contract/index.js';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const NETWORK = (process.env['NETWORK'] ?? 'preprod') as 'preprod' | 'preview';
const PROOF_SERVER_URL = process.env['PROOF_SERVER_URL'] ?? 'http://localhost:6300';
const __dirname = dirname(fileURLToPath(import.meta.url));
// ZK keys generated by `npm run compact`
const KEYS_DIR = join(__dirname, 'managed', 'ballot', 'keys');

// ---------------------------------------------------------------------------
// Deploy
// ---------------------------------------------------------------------------

async function deploy(): Promise<void> {
  console.log(`\nNight Ballot — deploying to Midnight ${NETWORK}`);
  console.log('─'.repeat(50));

  // 1. Resolve network environment (pre-configured Preprod/Preview URLs)
  const logger = createDefaultTestLogger();
  const env = NETWORK === 'preprod'
    ? new PreprodTestEnvironment(logger)
    : new PreviewTestEnvironment(logger);

  // Override proof server with locally running instance
  const envConfig = {
    ...env.getEnvironmentConfiguration(),
    proofServer: PROOF_SERVER_URL,
  };

  console.log(`Indexer  : ${envConfig.indexer}`);
  console.log(`Proof srv: ${envConfig.proofServer}`);

  // 2. Build a wallet from the BIP-39 mnemonic in WALLET_SEED
  const mnemonic = process.env['WALLET_SEED'];
  if (!mnemonic) throw new Error('WALLET_SEED must be set in .env (24-word BIP-39 mnemonic)');

  console.log('\nInitializing wallet from WALLET_SEED…');
  const walletProvider = await MidnightWalletProvider.build(logger, envConfig, mnemonic);

  console.log('Syncing wallet and waiting for funds…');
  // start() syncs the wallet with the indexer and waits for a non-zero balance
  await walletProvider.start(/* waitForFunds= */ true);

  // 3. Assemble midnight-js providers using the testkit helper
  const providers = initializeMidnightProviders<string, null>(
    walletProvider,
    envConfig,
    { privateStateStoreName: 'ballot-deploy', zkConfigPath: KEYS_DIR },
  );

  // Ballot contract has null private state — swap in the simple in-memory provider
  (providers as any).privateStateProvider = inMemoryPrivateStateProvider();

  // 4. Build Contract instance with the organizer key witness
  const witnesses = createWitnesses();
  const contract = new Contract({
    organizerKey: (_ctx: unknown) => [null, witnesses.organizerKey()] as [null, Uint8Array],
  });

  // 5. Deploy — proves, balances, and submits the deploy transaction
  console.log('\nCalling deployContract()…');
  const deployed = await deployContract(providers as any, {
    compiledContract: contract as any,
    privateStateId: 'ballot',
    initialPrivateState: null,
  } as any);

  await walletProvider.stop();

  const contractAddress = (deployed as any).deployTxData?.public?.contractAddress
    ?? String(deployed);

  const state = ledger((deployed as any).deployTxData?.public?.initialContractState?.data);

  console.log('\n✓ Contract deployed!');
  console.log(`  Address : ${contractAddress}`);
  console.log(`  Network : Midnight ${NETWORK}`);
  console.log(`  Is open : ${state.isOpen === 1n}`);
  console.log('\nAdd to .env:');
  console.log(`  CONTRACT_ADDRESS=${contractAddress}`);
  console.log('\nUpdate README.md:');
  console.log(`  | **Contract Address** | \`${contractAddress}\` (Midnight ${NETWORK}) |`);
}

deploy().catch((err) => {
  console.error('\nDeployment failed:', err);
  process.exit(1);
});
